{
	"version": 1687992974,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/playerimage-sheet0.png",
		"images/loadingbar.png",
		"images/solid.png",
		"images/camerazone-sheet0.png",
		"images/musiczone-sheet0.png",
		"images/checkpoint-sheet0.png",
		"images/checkpoint-sheet1.png",
		"images/spawnpoint-sheet0.png",
		"images/deathparticles.png",
		"images/death-sheet0.png",
		"images/bounce-sheet0.png",
		"images/semisolid-sheet0.png",
		"images/airjump-sheet0.png",
		"images/checkpointparticles.png",
		"images/levelfragment-sheet0.png",
		"images/fragmentparticles.png",
		"images/ice-sheet0.png",
		"images/water-sheet0.png",
		"images/gravity-sheet0.png",
		"images/trophy-sheet0.png",
		"images/dialogue.png",
		"images/eventzone-sheet0.png",
		"images/lightcaster-sheet0.png",
		"images/deathcount.png",
		"images/fragmentbar.png",
		"images/darker.png",
		"images/glitchysolid-sheet0.png",
		"images/pausedtext.png",
		"images/pausimation-sheet0.png",
		"media/airjump.m4a",
		"media/bigjump.m4a",
		"media/bigjump.ogg",
		"media/boost.m4a",
		"media/boost.ogg",
		"media/die.m4a",
		"media/enter field.m4a",
		"media/enter field.ogg",
		"media/exit field.m4a",
		"media/exit field.ogg",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/swim.m4a",
		"media/airjump.ogg",
		"media/die.ogg",
		"media/collect.m4a",
		"media/collect.ogg",
		"media/swim.ogg",
		"media/pop.m4a",
		"media/pop.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/chord.m4a",
		"media/chord.ogg",
		"media/last notes.m4a",
		"media/last notes.ogg",
		"media/count.m4a",
		"media/count.ogg",
		"media/kaboom.m4a",
		"media/kaboom.ogg",
		"media/looming-horizon-intro.m4a",
		"media/looming-horizon-intro.ogg",
		"media/looming-horizon.m4a",
		"media/looming-horizon.ogg",
		"media/lvl1.m4a",
		"media/lvl1.ogg",
		"media/bo'o'o'wa'a'.m4a",
		"media/bo'o'o'wa'a'.ogg",
		"media/flipped.m4a",
		"media/flipped.ogg",
		"media/help im drowning.m4a",
		"media/help im drowning.ogg",
		"media/learn.m4a",
		"media/learn.ogg",
		"media/lvl2.m4a",
		"media/lvl2.ogg",
		"media/lvl3.m4a",
		"media/lvl3.ogg",
		"media/lvl4.m4a",
		"media/lvl4.ogg",
		"media/lvl5.m4a",
		"media/lvl5.ogg",
		"media/lvl6.m4a",
		"media/lvl6.ogg",
		"media/lvl7&8.m4a",
		"media/lvl7&8.ogg",
		"media/purple.m4a",
		"media/purple.ogg",
		"media/slippery.m4a",
		"media/slippery.ogg",
		"media/i can see my house from here.m4a",
		"media/i can see my house from here.ogg",
		"media/breath.ogg",
		"media/get-ready.ogg",
		"media/think.ogg",
		"media/finale_music.ogg",
		"media/finale_music_intro.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"setup.js",
		"main.js",
		"obj_start.js",
		"player_tick.js",
		"object_tick.js",
		"events.js",
		"penumbra.png"
	]
}